spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autodump
    username: autodump_user
    password: root
    driver-class-name: org.postgresql.Driver

bot:
  token: 5990503214:AAGAlWdWPbKQCSvZsRfR9l48tAkuqTcFdws
  name: psa_dump_dev
commands:
  start: /start
  rules: /rules
  registration: /registration
  subscription: /subscription
  sale: /sale
validateData:
  channelID: -1001773791815
  channelURL: "https://t.me/dumpChenDev"

webApp:
  url: "https://dumpdot.ru"
  pathRegistration: "/registration"
  pathSale: "/sale"
  pathSearch: "/search"

resources:
  buttonsText:
    registration: Регистрация
    searchRequest: Найти
    placeAnAd: Продать
    withoutPhoto: Без фото
    rules: Правила
    newRequests: Новые запросы
    statistics: Статистика
    approved: Одобрить
    rejected: Отклонить
  errors:
    commonError: Что то пошло не так. Давай попробуем еще раз
    notAdminErr: Что то мне кажется, что ты не похож(а) на админа!
    authError: К сожалению, я не рапознал что ты подписан на канал. Для продолжения работы подпишись на канал и нажми /start
    userNameErr: Опа, у тебя отсутсвует имя пользователя. К сожалению, в такой ситуации регистрация невозможна. Укажи имя в настройках телеграм, и попробуй снова
  msgs:
    admin:
      welcome: Привет
      choice: Выбери действие, нажав кнопку ниже
      remember: Помни, люди на тебя надеятся. От тебя зависит успех продажи их товара!
      newAccommodation: Поступил новый запрос! Нажми на /admin, что бы посмотреть необработанные заявки!
      successApproved: успешно отправлен в канал. Пользователю отправлено соответсвующее сообщение
      upd: Запрос
      fromUser: от пользователя
      successApprovedForUser: Твой запрос был успешно проверен!
      successApprovedForUser2: Он размещен в канале, и доступен к просмотру. Найти его можешь в
      totalRequests: Всего не рассмотренных запросов
      statistics:
        registered: на текущий момент зарегистрировано пользователей
        cars: Присутствуют следующие автомобили
        inQuantity: в количестве
        things: шт
    welcomeMessage: Привет, добро пожаловать на свалку PSA. Для того что бы начать пользовататься свалкой - подпишись на канал {ссылка на канал}, и нажми на кнопку \"Регистрация\
    welcome: Привет, что хочешь сделать?
    registration:
      hello: Привет!
      go: Давай зарегистрируемся.
      description: После регистрации ты сможешь получать пересональные уведомления о новых обьявлениях по своей машине
      tapRegistration: Нажми на кнопку регистрация
    search:
      title: Хорошо, я запомнил что фото нет.
      botReady: Для отправки на модерацию - нажмми /ready
      successSendSearchQuery: Все хорошо, запрос на поиск запчасти отправлен на модерацию. Если он соответсвует правилам - скоро оно появится в канале
    sale:
      successSendQuery: Все хорошо, обьявление отправлено на модерацию. Если оно соответсвует правилам - скоро оно появится в канале
    photo:
      withOrWithoutPhoto: Если есть фото - отправь их мне. Если нет - то нажми на кнопку без фото
      noRegistration: К сожалению, я не вижу что ты зарегистрирован. Пройди регистрацию, для этого нажми /start
      givePhoto: Теперь прекрепи фотографии. Просто отправь их мне. Размещение объявления о продаже невозможно без фотографий
      noPhoto: Не нахожу у тебя фотографий.
      info: Размещение объявления о продаже невозможно без фотографий
      noAction: Не могу понять, зачем мне фото. что бы разместить их к обьявлению или запросу - сначала начни сначала нажми /start
      successSavedToLastCallBack: Отлично, фото добавлено! Для отправки на модерацию - нажмми /ready
  success:
    wonderful: Прекрасно!
    excellent: Отлично!
    successReservation: Ты успешно зарегистрирован
    possibilities: Теперь ты можешь размещать объявления и запросы на поиск деталей в канале.
    menuAccess: Что бы получить досуп у меню - нажми /start

  rules: Пока правил нет, ПОЛНАЯ АНАРХИЯ!!!!

