bot:
  token: 5990503214:AAGAlWdWPbKQCSvZsRfR9l48tAkuqTcFdws
  name: psa_dump_dev
webApp:
  url: "https://taupe-bienenstitch-397031.netlify.app"
  pathRegistration: "/registration"
  pathSale: ""
  pathSearch: ""
commands:
  start: /start
  rules: /rules
  registration: /registration
  subscription: /subscription
  sale: /sale

validateData:
  channelID: -1001773791815
  channelURL: "https://t.me/dumpChenDev"

storageConfig:
  login: autodump_user
  password: root
  sslMode: disable
  driverName: postgres
  databaseName: autodump
  attemptsConnection: 3
