CREATE USER autodump_user WITH password 'root';
ALTER USER autodump_user SUPERUSER;
CREATE DATABASE autodump OWNER autodump_user;

CREATE TABLE REGION
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(80) NOT NULL,
    country_code varchar(80) NOT NULL,
    region_id varchar(80) NOT NULL
);

INSERT INTO public.region (name, country_code, region_id) VALUES ('Костромская область'::varchar(80), 'RU'::varchar(80), '44'::varchar(80)),
('Республика Адыгея (Адыгея)'::varchar(80), 'RU'::varchar(80), '01'::varchar(80)),
('Курганская область'::varchar(80), 'RU'::varchar(80), '45'::varchar(80)),
('Ямало-Ненецкий автономный округ'::varchar(80), 'RU'::varchar(80), '89'::varchar(80)),
('Республика Башкортостан'::varchar(80), 'RU'::varchar(80), '02'::varchar(80)),
('Курская область'::varchar(80), 'RU'::varchar(80), '46'::varchar(80)),
('Республика Бурятия'::varchar(80), 'RU'::varchar(80), '03'::varchar(80)),
('Ленинградская область'::varchar(80), 'RU'::varchar(80), '47'::varchar(80)),
('Республика Алтай'::varchar(80), 'RU'::varchar(80), '04'::varchar(80)),
('Липецкая область'::varchar(80), 'RU'::varchar(80), '48'::varchar(80)),
('Республика Дагестан'::varchar(80), 'RU'::varchar(80), '05'::varchar(80)),
('Магаданская область'::varchar(80), 'RU'::varchar(80), '49'::varchar(80)),
('Республика Ингушетия'::varchar(80), 'RU'::varchar(80), '06'::varchar(80)),
('Кабардино-Балкарская Республика'::varchar(80), 'RU'::varchar(80), '07'::varchar(80)),
('Республика Калмыкия'::varchar(80), 'RU'::varchar(80), '08'::varchar(80)),
('Карачаево-Черкесская Республика'::varchar(80), 'RU'::varchar(80), '09'::varchar(80)),
('Республика Крым'::varchar(80), 'RU'::varchar(80), '91'::varchar(80)),
('г. Севастополь'::varchar(80), 'RU'::varchar(80), '92'::varchar(80)),
('Московская область'::varchar(80), 'RU'::varchar(80), '50'::varchar(80)),
('Мурманская область'::varchar(80), 'RU'::varchar(80), '51'::varchar(80)),
('Нижегородская область'::varchar(80), 'RU'::varchar(80), '52'::varchar(80)),
('Новгородская область'::varchar(80), 'RU'::varchar(80), '53'::varchar(80)),
('Республика Карелия'::varchar(80), 'RU'::varchar(80), '10'::varchar(80)),
('Новосибирская область'::varchar(80), 'RU'::varchar(80), '54'::varchar(80)),
('Республика Коми'::varchar(80), 'RU'::varchar(80), '11'::varchar(80)),
('Омская область'::varchar(80), 'RU'::varchar(80), '55'::varchar(80)),
('Иные территории, включая город и космодром Байконур'::varchar(80), 'RU'::varchar(80), '99'::varchar(80)),
('Республика Марий Эл'::varchar(80), 'RU'::varchar(80), '12'::varchar(80)),
('Оренбургская область'::varchar(80), 'RU'::varchar(80), '56'::varchar(80)),
('Республика Мордовия'::varchar(80), 'RU'::varchar(80), '13'::varchar(80)),
('Орловская область'::varchar(80), 'RU'::varchar(80), '57'::varchar(80)),
('Республика Саха (Якутия)'::varchar(80), 'RU'::varchar(80), '14'::varchar(80)),
('Пензенская область'::varchar(80), 'RU'::varchar(80), '58'::varchar(80)),
('Республика Северная Осетия - Алания'::varchar(80), 'RU'::varchar(80), '15'::varchar(80)),
('Пермский край'::varchar(80), 'RU'::varchar(80), '59'::varchar(80)),
('Республика Татарстан (Татарстан)'::varchar(80), 'RU'::varchar(80), '16'::varchar(80)),
('Республика Тыва'::varchar(80), 'RU'::varchar(80), '17'::varchar(80)),
('Удмуртская Республика'::varchar(80), 'RU'::varchar(80), '18'::varchar(80)),
('Республика Хакасия'::varchar(80), 'RU'::varchar(80), '19'::varchar(80)),
('Псковская область'::varchar(80), 'RU'::varchar(80), '60'::varchar(80)),
('Ростовская область'::varchar(80), 'RU'::varchar(80), '61'::varchar(80)),
('Рязанская область'::varchar(80), 'RU'::varchar(80), '62'::varchar(80)),
('Самарская область'::varchar(80), 'RU'::varchar(80), '63'::varchar(80)),
('Чеченская Республика'::varchar(80), 'RU'::varchar(80), '20'::varchar(80)),
('Саратовская область'::varchar(80), 'RU'::varchar(80), '64'::varchar(80)),
('Чувашская Республика - Чувашия'::varchar(80), 'RU'::varchar(80), '21'::varchar(80)),
('Сахалинская область'::varchar(80), 'RU'::varchar(80), '65'::varchar(80)),
('Алтайский край'::varchar(80), 'RU'::varchar(80), '22'::varchar(80)),
('Свердловская область'::varchar(80), 'RU'::varchar(80), '66'::varchar(80)),
('Краснодарский край'::varchar(80), 'RU'::varchar(80), '23'::varchar(80)),
('Смоленская область'::varchar(80), 'RU'::varchar(80), '67'::varchar(80)),
('Красноярский край'::varchar(80), 'RU'::varchar(80), '24'::varchar(80)),
('Тамбовская область'::varchar(80), 'RU'::varchar(80), '68'::varchar(80)),
('Приморский край'::varchar(80), 'RU'::varchar(80), '25'::varchar(80)),
('Тверская область'::varchar(80), 'RU'::varchar(80), '69'::varchar(80)),
('Ставропольский край'::varchar(80), 'RU'::varchar(80), '26'::varchar(80)),
('Хабаровский край'::varchar(80), 'RU'::varchar(80), '27'::varchar(80)),
('Амурская область'::varchar(80), 'RU'::varchar(80), '28'::varchar(80)),
('Архангельская область'::varchar(80), 'RU'::varchar(80), '29'::varchar(80)),
('Томская область'::varchar(80), 'RU'::varchar(80), '70'::varchar(80)),
('Тульская область'::varchar(80), 'RU'::varchar(80), '71'::varchar(80)),
('Тюменская область'::varchar(80), 'RU'::varchar(80), '72'::varchar(80)),
('Ульяновская область'::varchar(80), 'RU'::varchar(80), '73'::varchar(80)),
('Астраханская область'::varchar(80), 'RU'::varchar(80), '30'::varchar(80)),
('Челябинская область'::varchar(80), 'RU'::varchar(80), '74'::varchar(80)),
('Белгородская область'::varchar(80), 'RU'::varchar(80), '31'::varchar(80)),
('Забайкальский край'::varchar(80), 'RU'::varchar(80), '75'::varchar(80)),
('Брянская область'::varchar(80), 'RU'::varchar(80), '32'::varchar(80)),
('Ярославская область'::varchar(80), 'RU'::varchar(80), '76'::varchar(80)),
('Владимирская область'::varchar(80), 'RU'::varchar(80), '33'::varchar(80)),
('г. Москва'::varchar(80), 'RU'::varchar(80), '77'::varchar(80)),
('Волгоградская область'::varchar(80), 'RU'::varchar(80), '34'::varchar(80)),
('г. Санкт-Петербург'::varchar(80), 'RU'::varchar(80), '78'::varchar(80)),
('Вологодская область'::varchar(80), 'RU'::varchar(80), '35'::varchar(80)),
('Еврейская автономная область'::varchar(80), 'RU'::varchar(80), '79'::varchar(80)),
('Воронежская область'::varchar(80), 'RU'::varchar(80), '36'::varchar(80)),
('Ивановская область'::varchar(80), 'RU'::varchar(80), '37'::varchar(80)),
('Иркутская область'::varchar(80), 'RU'::varchar(80), '38'::varchar(80)),
('Калининградская область'::varchar(80), 'RU'::varchar(80), '39'::varchar(80)),
('Ненецкий автономный округ'::varchar(80), 'RU'::varchar(80), '83'::varchar(80)),
('Калужская область'::varchar(80), 'RU'::varchar(80), '40'::varchar(80)),
('Камчатский край'::varchar(80), 'RU'::varchar(80), '41'::varchar(80)),
('Кемеровская область'::varchar(80), 'RU'::varchar(80), '42'::varchar(80)),
('Ханты-Мансийский автономный округ - Югра'::varchar(80), 'RU'::varchar(80), '86'::varchar(80)),
('Кировская область'::varchar(80), 'RU'::varchar(80), '43'::varchar(80)),
('Чукотский автономный округ'::varchar(80), 'RU'::varchar(80), '87'::varchar(80)),
('Брестская область'::varchar(80), 'BY'::varchar(80), '1'::varchar(80)),
('Витебская область'::varchar(80), 'BY'::varchar(80), '2'::varchar(80)),
('Гомельская область'::varchar(80), 'BY'::varchar(80), '3'::varchar(80)),
('Гродненская область'::varchar(80), 'BY'::varchar(80), '4'::varchar(80)),
('Минская область'::varchar(80), 'BY'::varchar(80), '5'::varchar(80)),
('Могилёвская область'::varchar(80), 'BY'::varchar(80), '6'::varchar(80)),
('г. Минск'::varchar(80), 'BY'::varchar(80), '7'::varchar(80));

CREATE TABLE CAR
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concern      varchar(80),
    brand        varchar(80),
    model        varchar(80),
    engine       varchar(80),
    engine_type varchar(80),
    transmission varchar(80),
    bolt_pattern varchar(80),
    year_from    date,
    year_to      date,
    class        varchar(2)

);

CREATE TABLE CLIENT
(
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date     date                       NOT NULL,
    role             varchar(80)                NOT NULL,
    login            varchar(80)                NOT NULL UNIQUE,
    region_id        int REFERENCES REGION (id) NOT NULL,
    user_name        varchar(80)                NOT NULL,
    client_action    varchar(80),
    waiting_messages boolean                    NOT NULL,
    carid            int REFERENCES CAR (id)    NOT NULL,
    last_callBack    varchar(1000)
);

CREATE TABLE user_accommodation
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date date                       NOT NULL,
    type varchar(80)                NOT NULL,
    client_login varchar(80)                NOT NULL,
    client_id    int REFERENCES CLIENT (id) NOT NULL,
    min_price    int,
    max_price    int,
    approved     bool                       NOT NULL,
    rejected     bool                       NOT NULL,
    topical      bool                       NOT NULL,
    description  varchar(1000)              NOT NULL
);

CREATE TABLE user_accommodation_photo
(
    photo_id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id      varchar(225) NOT NULL,
    user_accommodation_id int NOT NULL REFERENCES user_accommodation (id)
);
