name: GitHub Actions

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
      - name: set -eu
        run: set -eu
      - name: mkdir "$HOME/.ssh"
        run: mkdir "$HOME/.ssh"
      - name: key
        run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - name: chmod
        run: chmod 600 "$HOME/.ssh/key"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          run: cd .. && cd /home/server && cat > filename.txt && rm log.txt
