name: GitHub Actions

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: testing build with Maven
        run: mvn -B package --file pom.xml
      - name: setup remote work...
        run: set -eu
      - name: still setting up...
        run: mkdir "$HOME/.ssh"
      - name: a little...
        run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - name: I'm ready!
        run: chmod 600 "$HOME/.ssh/key"
      - name: doing work on the server...
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd .. && 
                  cd /home/server/dumpBot/scripts &&
                  ./updateAndStart.sh

