name: GitHub Actions
run-name: ${{ github.actor }} is GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package